[build]
  publish = "."

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
  force = true
